### ISSUE TITLE
Quantity of 0 pluralized

### ISSUE THREAD

**Issue by mewhit** [GlobalWebIndex/elm-plural-rules#6]
Maybe I am wrong but, When n is 0, we should use singular ?

**Comment by Janiczek** [comment]
I believe zero should be plural:

As a non-native English speaker I've opted to not implement rules that "feel right" but use rules defined by somebody else. Unicode consortium felt like a safe bet of an "authority". They have [this page](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html) listing the rules for various languages.

Here is the screenshot of the English section:

![English rules](https://raw.githubusercontent.com/GlobalWebIndex/elm-plural-rules/master/docs/en.png)

There are also discussions about this on Stack Exchange if you're interested: https://english.stackexchange.com/questions/38293/why-is-zero-followed-by-a-plural-noun#
